name: Deploy to pages

on:
  workflow_dispatch:
    
  push:
    branches:
      - main
      - release

jobs:

  build:
    permissions:
       contents: write

    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: prepare
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 17
 
      - name: Install
        run: yarn build
      - name: Copy CNAME
        run: cp CNAME dist/CNAME
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: dist
           
      

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
       contents: write
       deployments: write
       pages: write
    steps:
      - uses: actions/download-artifact@v4
        id: artf
            
            
      - name: Display structure of downloaded files
        run: ls -R 
      
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:  ${{steps.artf.outputs.download-path	}}
          publish_branch: gh-pages
